<%@ Control Language="C#" AutoEventWireup="true" CodeBehind="SubGG.ascx.cs" Inherits="JDJS.Web.Controls.SubGG" %>
<div class="SubGG">
    <a target="_blank" href="http://www.shhsdl.com.cn/"><img style="width:136px; height:83px; border:1px #aaaaaa solid; padding:2px;" alt="宏胜电缆" src="uploads/gg4.gif" /></a>
    <a target="_blank" href="http://www.xlxfjc.com/"><img style="width:136px; height:83px; border:1px #aaaaaa solid; padding:2px; margin-top:2px;" alt="希黎消防" src="uploads/gg4-1.gif" /></a>
    <a target="_blank" href="http://www.hippos.cn/"><img style=" width:136px; height:83px; border:1px #aaaaaa solid; padding:2px;  margin-top:2px;" alt="河马井" src="uploads/hemaLGO.jpg" /></a>
    <a target="_blank" href="http://www.shkxgt.com/"><img style=" width:136px; height:83px; border:1px #aaaaaa solid; padding:2px;  margin-top:2px;" alt="奎鑫钢铁" src="uploads/kxright.jpg" /></a>
    <a target="_blank" href="http://www.sh-zhenda.com/"><img style=" width:136px; height:83px; border:1px #aaaaaa solid; padding:2px;  margin-top:2px;" alt="振大电器" src="uploads/zdright.gif" /></a>
    <a target="_blank" href="http://www.jdjs.com.cn#"><img style=" width:136px; height:670px;border:1px #aaaaaa solid; padding:2px;margin-top:2px; " alt="建定官方微信、建定通APP二维码" src="uploads/2014ewm.JPG" /></a>
  <!-- <a target="_blank" href=""><img style="width:136px; height:83px; border:1px #aaaaaa solid; padding:2px;" alt="" src="uploads/gg4.gif" /></a><a href=""><img style="width:136px; height:83px; border:1px #aaaaaa solid; padding:2px; margin-top:2px;" alt="" src="uploads/gg4-1.gif" /></a><a target="_blank" href=""><img style=" width:136px; height:83px; border:1px #aaaaaa solid; padding:2px;  margin-top:2px;" alt="" src="uploads/gg4-2.gif" /></a><a target="_blank" href="#"><img style=" width:136px; height:670px;border:1px #aaaaaa solid; padding:2px;margin-top:2px; " alt="" src="uploads/gg4-3.gif" /></a>-->
</div>