<a href="http://freelanceswitch.com/" target="_blank" title="点击直接访问"><img class='pic1' src='http://seanloo.cn/upload/2009/7/freelanceswitch.gif'></a>
<a href="http://www.cyber-eyes.net/" target="_blank" title="点击直接访问"><img class='pic1' src='http://seanloo.cn/upload/2009/7/cyber-eyes.gif'></a>
<a href="http://foodincmovie.com/" target="_blank" title="点击直接访问"><img class='pic1' src='http://seanloo.cn/upload/2009/7/foodincmovie.jpg'></a>
<a href="http://www.pampaneo.es/" target="_blank" title="点击直接访问"><img class='pic1' src='http://seanloo.cn/upload/2009/7/pampaneo.jpg'></a>