<div id="content_1">
<div id="content_pic">
      <div id="focus">
        <div id="No">
          <ul>
            <li class="bbg1" id="t0" onmouseover="Mea(0);clearAuto();" onmouseout="setAuto()">1</li>
            <li class="bbg0" id="t1" onmouseover="Mea(1);clearAuto();" onmouseout="setAuto()">2</li>
            <li class="bbg0" id="t2" onmouseover="Mea(2);clearAuto();" onmouseout="setAuto()">3</li>
            <li class="bbg0" id="t3" onmouseover="Mea(3);clearAuto();" onmouseout="setAuto()">4</li>
            <li class="bbg0" id="t4" onmouseover="Mea(4);clearAuto();" onmouseout="setAuto()">5</li>
          </ul>
        </div>
        <div id="au">
          <div style="display:block"><a href="http://seanloo.cn/post/149.html" rel="external" target="_blank"><img src="http://seanloo.cn/upload/2009/7/200907241241463505.jpg" /></a></div>
          <div style="display:none"><a href="http://seanloo.cn/post/148.html" rel="external" target="_blank"><img src="http://seanloo.cn/upload/2009/7/200907241233111352.jpg" /></a></div>
          <div style="display:none"><a href="http://seanloo.cn/post/145.html" rel="external" target="_blank"><img src="http://seanloo.cn/upload/2009/7/200907210921141785.jpg" /></a></div>
          <div style="display:none"><a href="javascript:void(0)" rel="external" target="_blank"><img src="http://seanloo.cn/upload/2009/7/tshows.jpg" /></a></div>
          <div style="display:none"><a href="http://seanloo.cn/post/132.html" rel="external" target="_blank"><img src="http://seanloo.cn/upload/2009/7/transforamt.jpg" /></a></div>
        </div>
        <div id="conau">
          <div style="display:block">《哈利波特与混血王子》十大看点(组图)</div>
          <div style="display:none">80后夫妻《吵架公约》当家规，实在是高！</div>
          <div style="display:none">"世纪日全食"观看全攻略</div>
          <div style="display:none">想参与Tshows特秀的活动，现在就加入到秀客的行列吧</div>
          <div style="display:none">《变形金刚2》预告片分镜头讲解</div>
          </div>
        <div class="clear"></div>
      </div>
</div>
</div>